name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Setup test environment
      run: |
        mkdir -p test_uploads/resumes
        mkdir -p test_uploads/cover_letters
    
    - name: Run tests
      env:
        DATABASE_URL: sqlite:///./test.db
        SECRET_KEY: test-secret-key
        UPLOAD_DIR_RESUME: test_uploads/resumes
        UPLOAD_DIR_COVER_LETTER: test_uploads/cover_letters
        ALLOWED_EXTENSIONS: ".pdf,.doc,.docx"
        MAX_FILE_SIZE: "5242880"  # 5MB in bytes
      run: |
        export PYTHONPATH=src
        pytest --cov=app -v